/* Grammar — the rules, laid out, with a way straight into practising them.

   The app had a word list and eight games and nothing in between. She could
   drill conjugation but not look up a table; she could be told der Hund is
   masculine but never see the pattern behind it. This is the missing
   middle: read the rule, browse the forms, then jump into the game that
   drills exactly what she has just read.

   That last part is the point. A reference nobody acts on is a document.
   Every topic here ends with a button into the matching game, and every
   game already exists — nothing new is being taught, it is being explained
   before it is tested.

   Nothing here needs new content. The verb tables are generated by
   conjugate.js, the gender counts come from vocab.js, the case examples
   from case.js. */

window.GH = window.GH || {};

GH.grammar = (function(){

  var host = null, state = null;

  function t(k, v){ return GH.i18n.t(k, v); }

  function el(tag, cls, text){
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text !== undefined && text !== null) n.textContent = text;
    return n;
  }

  /* ---------- what the app can explain today ---------- */

  function verbGroups(){
    var C = GH.conjugate;
    var fromVocab = (window.GH_VOCAB || []).map(function(v){
      return v.de.split(/\s+/).pop();
    }).filter(function(w){
      return /^[a-zäöüß]/.test(w) && /(en|ern|eln)$/.test(w) && w.length > 3 && C.isVerb(w);
    });
    var all = {};
    fromVocab.forEach(function(v){ all[v] = 1; });
    Object.keys(C.irregulars).forEach(function(v){ all[v] = 1; });

    var by = {};
    Object.keys(all).forEach(function(v){
      var k = C.kind(v);
      (by[k] = by[k] || []).push(v);
    });
    Object.keys(by).forEach(function(k){ by[k].sort(); });
    return by;
  }

  var TOPICS = [
    { id:'irregular', glyph:'🔀', key:'grIrregular', game:'conjugate' },
    { id:'shift',     glyph:'🔤', key:'grShift',     game:'conjugate' },
    { id:'regular',   glyph:'📗', key:'grRegular',   game:'conjugate' },
    { id:'gender',    glyph:'⚖️', key:'grGender',    game:'gender' },
    { id:'case',      glyph:'📍', key:'grCase',      game:'wo-wohin' },
    { id:'plural',    glyph:'👥', key:'grPlural',    game:'mehrzahl' },
    { id:'order',     glyph:'🧩', key:'grOrder',     game:'scramble' },
    { id:'past',      glyph:'⏮️', key:'grPast',      game:null },
    { id:'future',    glyph:'⏭️', key:'grFuture',    game:null }
  ];

  function countFor(id){
    var g = verbGroups();
    if (id === 'irregular') return (g.irregular || []).length;
    if (id === 'regular')   return (g.regular || []).length;
    if (id === 'shift'){
      return ['e-ie','e-i','a-ä','au-äu'].reduce(function(a, k){
        return a + (g[k] || []).length;
      }, 0);
    }
    if (id === 'gender'){
      return (window.GH_VOCAB || []).filter(function(v){
        return /^(der|die|das) [A-ZÄÖÜ][a-zäöüß]+$/.test(v.de);
      }).length;
    }
    if (id === 'case') return ((window.GH_CASE || {}).pairs || []).length;
    if (id === 'plural') return (window.GH_PLURALS || []).length;
    if (id === 'order') return orderExamples().length;
    if (id === 'past') return (window.GH_PAST || []).length;
    if (id === 'future') return ((window.GH_FUTURE || {}).verbs || []).length;
    return 0;
  }

  /* Sentences where the verb is not where a Russian speaker would put it.
     Drawn from the bank rather than written, so every example is one she
     has already met somewhere. */
  function orderExamples(){
    var out = [];
    ((window.GH_BANK || {}).sentences || []).forEach(function(s){ out.push(s); });
    ((window.GH_BANK || {}).stories || []).forEach(function(st){
      st.sentences.forEach(function(l){ out.push(l); });
    });
    (window.GH_SONGS || []).forEach(function(song){
      Object.keys(song.lines).forEach(function(id){ out.push(song.lines[id]); });
    });
    return out;
  }

  /* ---------- the list of topics ---------- */

  function paintList(){
    host.textContent = '';

    var head = el('div', 'practice-head');
    var back = el('button', 'backlink', '‹ ' + t('back'));
    back.type = 'button';
    back.addEventListener('click', function(){ state.onExit(); });
    head.appendChild(back);
    var titles = el('div', 'practice-title');
    titles.appendChild(el('h1', null, t('grTitle')));
    titles.appendChild(el('p', null, t('grSub')));
    head.appendChild(titles);
    host.appendChild(head);

    var grid = el('div', 'tiles');
    TOPICS.forEach(function(tp){
      var n = countFor(tp.id);
      var b = el('button', 'tile');
      b.type = 'button';
      b.disabled = !n;
      b.appendChild(el('span', 'tile-glyph', tp.glyph));
      b.appendChild(el('span', 'tile-name', t(tp.key)));
      b.appendChild(el('span', 'tile-sub', t(tp.key + 'Sub')));
      b.appendChild(el('span', 'tile-foot', t('grItemsN', { n:n })));
      b.addEventListener('click', function(){ state.topic = tp; paintTopic(); });
      grid.appendChild(b);
    });
    host.appendChild(grid);
  }

  /* ---------- one topic ---------- */

  function practiseButton(tp){
    /* some topics have no game yet — the past tense is explained here long
       before anything drills it, and a button leading nowhere is worse
       than no button */
    if (!tp.game) return document.createTextNode('');
    var wrap = el('div', 'gr-practise');
    wrap.appendChild(el('p', 'gr-practise-l', t('grReadyQ')));
    var b = el('button', 'btn btn-primary js-advance', t('grPractise'));
    b.type = 'button';
    b.addEventListener('click', function(){
      /* hand straight over to the game this topic explains */
      var a = GH.app.find && GH.app.find(tp.game);
      if (!a) { state.onExit(); return; }
      host.textContent = '';
      GH.speech.stop();
      a.open(host, function(){ state.topic = tp; paintTopic(); });
    });
    wrap.appendChild(b);
    return wrap;
  }

  function topicHead(tp){
    var head = el('div', 'practice-head');
    var back = el('button', 'backlink', '‹ ' + t('back'));
    back.type = 'button';
    back.addEventListener('click', function(){ state.topic = null; paintList(); });
    head.appendChild(back);
    var titles = el('div', 'practice-title');
    titles.appendChild(el('h1', null, t(tp.key)));
    /* No subtitle. It used to repeat 'Grammar' under the topic name,
       which is a breadcrumb to the page you just left and is already
       written on the Back button two inches above it. */
    head.appendChild(titles);
    return head;
  }

  function verbTopic(tp, keys){
    var g = verbGroups();
    var list = [];
    keys.forEach(function(k){ list = list.concat(g[k] || []); });
    list = list.filter(function(v, i, a){ return a.indexOf(v) === i; }).sort();

    var card = el('div', 'card');
    card.appendChild(el('p', 'gr-lede', t(tp.key + 'Lede')));

    /* the vowel-shift group is only teachable as families, so it is split */
    if (tp.id === 'shift'){
      [['e-ie','e → ie'], ['e-i','e → i'], ['a-ä','a → ä'], ['au-äu','au → äu']]
        .forEach(function(pair){
          var members = (g[pair[0]] || []);
          if (!members.length) return;
          card.appendChild(el('h2', 'gr-group', pair[1]));
          members.sort().forEach(function(v){
            card.appendChild(GH.verbTable.render(v, {}));
          });
        });
    } else {
      list.forEach(function(v){ card.appendChild(GH.verbTable.render(v, {})); });
    }

    card.appendChild(practiseButton(tp));
    return card;
  }

  function genderTopic(tp){
    var V = (window.GH_VOCAB || []).filter(function(v){
      return /^(der|die|das) [A-ZÄÖÜ][a-zäöüß]+$/.test(v.de);
    });
    var art = function(v){ return v.de.split(' ')[0]; };
    var RU = { der:'M', die:'F', das:'N' };
    var counts = { der:0, die:0, das:0 };
    V.forEach(function(v){ counts[art(v)]++; });
    var differ = V.filter(function(v){
      return v.rg && v.rg !== 'PL' && RU[art(v)] !== v.rg;
    });

    var card = el('div', 'card');
    card.appendChild(el('p', 'gr-lede', t('grGenderLede')));

    var row = el('div', 'gr-stats');
    [['der', counts.der], ['die', counts.die], ['das', counts.das]].forEach(function(p){
      var b = el('div', 'gr-stat');
      b.appendChild(el('span', 'gr-stat-a', p[0]));
      b.appendChild(el('span', 'gr-stat-n', p[1]));
      row.appendChild(b);
    });
    card.appendChild(row);

    card.appendChild(el('h2', 'gr-group', t('grGenderClash', { n:differ.length })));
    card.appendChild(el('p', 'gr-note', t('grGenderClashNote')));

    var lang = GH.i18n.lang();
    var tbl = el('div', 'gr-pairs');
    differ.slice(0, 40).forEach(function(v){
      var r = el('button', 'gr-pair');
      r.type = 'button';
      r.appendChild(el('span', 'gr-pair-de', v.de));
      r.appendChild(el('span', 'gr-pair-ru', (v.ru || '') + ' · ' + t('gnGender_' + v.rg)));
      r.addEventListener('click', function(){ GH.speech.say(v.de); });
      tbl.appendChild(r);
    });
    card.appendChild(tbl);
    if (differ.length > 40){
      card.appendChild(el('p', 'gr-note', t('grAndMore', { n:differ.length - 40 })));
    }

    card.appendChild(practiseButton(tp));
    return card;
  }

  function caseTopic(tp){
    var C = window.GH_CASE || { pairs:[], fixed:[] };
    var card = el('div', 'card');
    card.appendChild(el('p', 'gr-lede', t('grCaseLede')));

    var grid = el('div', 'gr-caserow');
    [[t('wwWo'), 'dem · der · dem', 'dat'], [t('wwWohin'), 'den · die · das', 'acc']]
      .forEach(function(c){
        var b = el('div', 'gr-casecell gr-' + c[2]);
        b.appendChild(el('span', 'gr-case-l', c[0]));
        b.appendChild(el('span', 'gr-case-f', c[1]));
        grid.appendChild(b);
      });
    card.appendChild(grid);

    card.appendChild(el('h2', 'gr-group', t('grCaseNine')));
    card.appendChild(el('p', 'gr-preps', 'in · auf · an · über · unter · neben · vor · hinter · zwischen'));

    /* a worked pair says more than the rule does */
    var lang = GH.i18n.lang();
    C.pairs.slice(0, 8).forEach(function(p){
      var box = el('div', 'ww-pair');
      [['pos', 'wwWo'], ['mot', 'wwWohin']].forEach(function(row){
        var side = el('button', 'ww-side');
        side.type = 'button';
        side.appendChild(el('span', 'ww-side-l', t(row[1])));
        side.appendChild(el('span', 'ww-side-de', p[row[0]].de));
        if (lang !== 'de') side.appendChild(el('span', 'ww-side-tr', p[row[0]][lang] || ''));
        side.addEventListener('click', function(){ GH.speech.say(p[row[0]].de); });
        box.appendChild(side);
      });
      card.appendChild(box);
    });

    card.appendChild(el('h2', 'gr-group', t('grCaseFixed')));
    card.appendChild(el('p', 'gr-note', t('grCaseFixedNote')));

    card.appendChild(practiseButton(tp));
    return card;
  }

  /* The five plural families, each with three worked examples. Seeing
     der Junge → die Jungen beside die Tasche → die Taschen is what makes
     -n look like a rule rather than two facts. */
  function pluralTopic(tp){
    var P = window.GH_PLURALS || [];
    var FAM = [
      ['n',    ['n','en'],        'mzFamN'],
      ['e',    ['e','ue'],        'mzFamE'],
      ['same', ['same','usame'],  'mzFamSame'],
      ['er',   ['er','uer'],      'mzFamEr'],
      ['s',    ['s'],             'mzFamS']
    ];
    var card = el('div', 'card');
    card.appendChild(el('p', 'gr-lede', t('grPluralLede')));

    var banner = el('p', 'gr-banner', t('mzAlwaysDie'));
    card.appendChild(banner);

    FAM.forEach(function(f){
      var list = P.filter(function(x){ return f[1].indexOf(x.p) >= 0; });
      if (!list.length) return;
      var h = el('h2', 'gr-group', t(f[2]));
      h.appendChild(el('span', 'gr-count', t('grItemsN', { n:list.length })));
      card.appendChild(h);
      card.appendChild(el('p', 'gr-note', t('mzWhy_' + f[0])));
      var rows = el('div', 'gr-pairs');
      list.slice(0, 4).forEach(function(x){
        var r = el('button', 'gr-pair');
        r.type = 'button';
        r.appendChild(el('span', 'gr-pair-de', x.sg + '  →  ' + x.pl));
        r.appendChild(el('span', 'gr-pair-ru', GH.i18n.lang() === 'ru' ? (x.ru || '') : (x.en || '')));
        r.addEventListener('click', function(){ GH.speech.say(x.sg + ' … ' + x.pl); });
        rows.appendChild(r);
      });
      card.appendChild(rows);
    });

    var none = P.filter(function(x){ return x.p === 'none'; });
    if (none.length){
      card.appendChild(el('h2', 'gr-group', t('grNoPluralHead')));
      card.appendChild(el('p', 'gr-note', t('grNoPluralNote')));
      card.appendChild(el('p', 'gr-preps',
        none.slice(0, 12).map(function(x){ return x.sg; }).join(' · ')));
    }

    card.appendChild(practiseButton(tp));
    return card;
  }

  /* Verb-second means the second *position*, not the second word — 'Zum
     Frühstück' is one position, so the verb is third along. Marking word
     two would have highlighted 'Frühstück' and taught the wrong rule. So
     the finite verb is found rather than assumed: every form of every verb
     the conjugator knows, gathered once, then matched against the
     sentence. */
  var verbForms = null;
  function finiteForms(){
    if (verbForms) return verbForms;
    var set = {};
    var seen = {};
    (window.GH_VOCAB || []).forEach(function(v){
      var w = v.de.split(/\s+/).pop();
      /* the same shape test the verb lists use — an infinitive ends in
         -en, -ern or -eln, and without that check 'heute' walks straight in */
      if (!/^[a-zäöüß]/.test(w) || !/(en|ern|eln)$/.test(w) || w.length <= 3
          || !GH.conjugate.isVerb(w) || seen[w]) return;
      seen[w] = 1;
      GH.conjugate.forms(w).forEach(function(f){ set[f.toLowerCase()] = 1; });
    });
    Object.keys(GH.conjugate.irregulars).forEach(function(v){
      GH.conjugate.forms(v).forEach(function(f){ set[f.toLowerCase()] = 1; });
    });
    verbForms = set;
    return set;
  }

  function verbAt(words){
    var set = finiteForms();
    for (var i = 0; i < words.length; i++){
      var w = words[i].replace(/[.,!?;:]/g, '').toLowerCase();
      if (set[w]) return i;
    }
    return -1;
  }

  function orderTopic(tp){
    var card = el('div', 'card');
    card.appendChild(el('p', 'gr-lede', t('grOrderLede')));

    var all = orderExamples();
    var lang = GH.i18n.lang();

    function block(headKey, noteKey, re, mark){
      var list = all.filter(function(s){ return re.test(s.de); }).slice(0, 5);
      if (!list.length) return;
      card.appendChild(el('h2', 'gr-group', t(headKey)));
      card.appendChild(el('p', 'gr-note', t(noteKey)));
      list.forEach(function(s){
        var r = el('button', 'gr-sent');
        r.type = 'button';
        /* light up the verb so the position is visible, not just described */
        var words = s.de.split(/\s+/);
        var at = mark(words);
        words.forEach(function(w, i){
          var span = el('span', i === at ? 'gr-verb' : null, w);
          r.appendChild(span);
          if (i < words.length - 1) r.appendChild(document.createTextNode(' '));
        });
        if (lang !== 'de' && s[lang]) r.appendChild(el('span', 'gr-sent-tr', s[lang]));
        r.addEventListener('click', function(){ GH.speech.say(s.de); });
        card.appendChild(r);
      });
    }

    block('grOrderV2', 'grOrderV2Note',
      /^(Heute|Morgen|Am|Im|Jetzt|Dann|Später|Nach|Danach|Zuerst|Manchmal|Abends|Zum|Gestern)\b/,
      function(words){ return verbAt(words); });

    /* in a subordinate clause the verb is the last word before the stop */
    block('grOrderEnd', 'grOrderEndNote',
      /\b(weil|dass|wenn)\b/,
      function(words){ return words.length - 1; });

    card.appendChild(practiseButton(tp));
    return card;
  }

  /* The past tense. German has two, and the reason for both is the lesson:
     one is spoken, one is written, and a learner who knows only the spoken
     one cannot read a story. */
  function pastTopic(tp){
    var P = window.GH_PAST || [];
    var lang = GH.i18n.lang();
    var card = el('div', 'card');
    card.appendChild(el('p', 'gr-lede', t('grPastLede')));

    /* the two tenses, side by side, because the difference is the point */
    var two = el('div', 'gr-caserow');
    [['grPastPerfekt', 'grPastPerfektNote', 'dat'],
     ['grPastPrat',    'grPastPratNote',    'acc']].forEach(function(c){
      var b = el('div', 'gr-casecell gr-' + c[2]);
      b.appendChild(el('span', 'gr-case-l', t(c[0])));
      b.appendChild(el('span', 'gr-case-f', t(c[1])));
      two.appendChild(b);
    });
    card.appendChild(two);

    card.appendChild(el('p', 'gr-banner', t('grPastAux')));

    /* Weak first because it is a rule she can apply immediately, then
       strong because there is no rule and the list has to be met, then
       mixed because it only makes sense once she knows what it is mixing. */
    var stepN = 0;
    [['weak',   'grPastWeak',   'grPastWeakNote'],
     ['strong', 'grPastStrong', 'grPastStrongNote'],
     ['mixed',  'grPastMixed',  'grPastMixedNote']].forEach(function(g){
      var list = P.filter(function(x){ return x.c === g[0]; });
      if (!list.length) return;
      stepN++;
      var h = el('h2', 'gr-step');
      h.appendChild(el('span', 'gr-step-n', stepN));
      h.appendChild(el('span', 'gr-step-t', t(g[1])));
      h.appendChild(el('span', 'gr-count', t('grItemsN', { n:list.length })));
      card.appendChild(h);
      card.appendChild(el('p', 'gr-note', t(g[2])));

      var tbl = el('div', 'gr-past');
      list.forEach(function(x){
        var r = el('button', 'gr-past-row' + (x.aux === 'sein' ? ' is-sein' : ''));
        r.type = 'button';
        r.appendChild(el('span', 'gr-past-inf', x.v));
        r.appendChild(el('span', 'gr-past-pt', x.pt));
        r.appendChild(el('span', 'gr-past-pp',
          (x.aux === 'sein' ? 'ist ' : 'hat ') + x.pp));
        r.addEventListener('click', function(){ GH.speech.say(x.de); });
        tbl.appendChild(r);

        var ex = el('div', 'gr-past-ex');
        ex.appendChild(el('span', 'gr-past-de', x.de));
        if (lang !== 'de' && x[lang]) ex.appendChild(el('span', 'gr-past-tr', x[lang]));
        tbl.appendChild(ex);
      });
      card.appendChild(tbl);
    });

    card.appendChild(el('h2', 'gr-group', t('grPastRussian')));
    card.appendChild(el('p', 'gr-note', t('grPastRussianNote')));

    return card;
  }

  /* The future, where the interesting fact is that German largely manages
     without one. Two columns rather than a table, because the whole lesson
     is that these are two ways of saying the same thing. */
  /* A numbered step, so the page reads as a route rather than a pile. */
  function step(card, n, titleKey, noteKey){
    var h = el('h2', 'gr-step');
    h.appendChild(el('span', 'gr-step-n', n));
    h.appendChild(el('span', 'gr-step-t', t(titleKey)));
    card.appendChild(h);
    if (noteKey) card.appendChild(el('p', 'gr-note', t(noteKey)));
  }

  /* The future in three steps rather than all at once.

     Learn werden first, even though it is the less common form, because
     it is the one that is unambiguously future — three distinct forms,
     nothing to confuse. Only then the everyday version, which is the
     present tense wearing a time word, and which cannot be recognised
     from the verb at all. Doing it the other way round means starting
     with an ambiguity, and she has nothing yet to resolve it against.

     The trap comes last, when both forms are solid enough that a third
     meaning of werden will not knock them over. */
  function futureTopic(tp){
    var F = window.GH_FUTURE || { verbs:[], markers:[] };
    var lang = GH.i18n.lang();
    var card = el('div', 'card');
    card.appendChild(el('p', 'gr-lede', t('grFutureLede')));
    card.appendChild(el('p', 'gr-banner', t('grFutureRoute')));

    step(card, 1, 'grFutureWerden', 'grFutureWerdenNote');
    card.appendChild(GH.verbTable.render('werden', {}));
    card.appendChild(el('p', 'gr-note', t('grFutureStep1End')));

    step(card, 2, 'grFutureWhen', 'grFutureWhenNote');
    var marks = el('div', 'gr-marks');
    F.markers.forEach(function(m){
      var b = el('button', 'gr-mark');
      b.type = 'button';
      b.appendChild(el('span', 'gr-mark-de', m.de));
      if (lang !== 'de') b.appendChild(el('span', 'gr-mark-tr', m[lang] || m.en));
      b.addEventListener('click', function(){ GH.speech.say(m.de); });
      marks.appendChild(b);
    });
    card.appendChild(marks);

    step(card, 3, 'grFutureBoth', 'grFutureBothNote');
    F.verbs.forEach(function(x){
      var pair = el('div', 'gr-fut');
      [['now', 'grFutureEveryday'], ['futur', 'grFutureFormal']].forEach(function(side){
        var b = el('button', 'gr-fut-side gr-fut-' + side[0]);
        b.type = 'button';
        b.appendChild(el('span', 'gr-fut-l', t(side[1])));
        b.appendChild(el('span', 'gr-fut-de', x[side[0]]));
        b.addEventListener('click', function(){ GH.speech.say(x[side[0]]); });
        pair.appendChild(b);
      });
      if (lang !== 'de' && x[lang]) pair.appendChild(el('span', 'gr-fut-tr', x[lang]));
      card.appendChild(pair);
    });

    step(card, 4, 'grFutureTrap', 'grFutureTrapNote');
    card.appendChild(el('p', 'gr-preps', 'Ich werde Lehrer.   \u00b7   Ich werde arbeiten.'));

    card.appendChild(el('h2', 'gr-group', t('grFutureRussian')));
    card.appendChild(el('p', 'gr-note', t('grFutureRussianNote')));

    return card;
  }

  function paintTopic(){
    host.textContent = '';
    var tp = state.topic;
    host.appendChild(topicHead(tp));

    if (tp.id === 'irregular') host.appendChild(verbTopic(tp, ['irregular']));
    else if (tp.id === 'shift') host.appendChild(verbTopic(tp, ['e-ie','e-i','a-ä','au-äu']));
    else if (tp.id === 'regular') host.appendChild(verbTopic(tp, ['regular']));
    else if (tp.id === 'gender') host.appendChild(genderTopic(tp));
    else if (tp.id === 'case') host.appendChild(caseTopic(tp));
    else if (tp.id === 'plural') host.appendChild(pluralTopic(tp));
    else if (tp.id === 'order') host.appendChild(orderTopic(tp));
    else if (tp.id === 'past') host.appendChild(pastTopic(tp));
    else if (tp.id === 'future') host.appendChild(futureTopic(tp));

    GH.nav.ready();
  }

  function open(container, onExit){
    host = container;
    state = { onExit:onExit, topic:null };
    paintList();
  }

  /* Jump straight to one topic. The coach uses this when it has worked out
     which rule is going wrong — landing her on the index and asking her to
     find it herself would waste the moment. */
  function openTopic(container, id, onExit){
    var tp = null;
    for (var i = 0; i < TOPICS.length; i++) if (TOPICS[i].id === id) tp = TOPICS[i];
    host = container;
    state = { onExit:onExit, topic:tp };
    /* WHICH grammar topic she read. Nine topics behind one tile, and the
       coach sends her here by name — so knowing she read `case` and then
       still failed the case lesson is the strongest teaching signal the app
       can produce. */
    if (tp && GH.events && GH.events.mark) GH.events.mark('read', 'grammar:' + tp.id);
    if (tp) paintTopic(); else paintList();
  }

  /* ---------- A RULE READ WITHOUT LEAVING ----------

     Everything that sent her to a grammar page used to destroy the screen
     she was on: `host.textContent = ''` and then render the topic into the
     same container. So reading the rule cost her the round, and coming back
     meant starting a fresh one — every activity's `open()` resets its state,
     so there is nothing to resume once the view is gone.

     A Return button could not have fixed that. It would have re-opened the
     activity at question one.

     So this opens OVER the page instead, exactly as howto.js does and for
     the reason written at the top of that file: she can check the rule
     mid-round without losing her place. Nothing behind it is touched, so
     Return really does return — the round is still there, mid-question,
     with her streak intact.

     `onClose` is optional. The Return button and the backdrop both close. */
  var over = null;

  function overlayOpen(){
    return !!(over && over.className.indexOf('is-open') >= 0);
  }

  function closeOverlay(){
    if (!over) return;
    over.className = 'gr-overlay';
    over.textContent = '';
    document.body.style.overflow = '';
    /* The activity behind may have armed nav before we covered it; re-arm so
       its advance button takes the keyboard back. */
    if (GH.nav && GH.nav.ready) GH.nav.ready();
    var then = over._then;
    over._then = null;
    if (then) then();
  }

  /* `topic` is a topic id, or null for the index. */
  function overlay(topic, onClose){
    if (!over){
      over = el('div', 'gr-overlay');
      over.setAttribute('role', 'dialog');
      over.setAttribute('aria-modal', 'true');
      over.addEventListener('click', function(e){
        if (e.target === over) closeOverlay();
      });
      document.body.appendChild(over);
    }
    over.textContent = '';
    over._then = onClose || null;

    var box = el('div', 'gr-over-box');

    /* Return sits at the top, where the back link would be, because that is
       where she will look for the way out. */
    var bar = el('div', 'gr-over-bar');
    var back = el('button', 'backlink gr-over-back', '\u2039 ' + t('back'));
    back.type = 'button';
    back.addEventListener('click', closeOverlay);
    bar.appendChild(back);
    var ret = el('button', 'btn btn-primary gr-over-return', t('grReturn'));
    ret.type = 'button';
    ret.addEventListener('click', closeOverlay);
    bar.appendChild(ret);
    box.appendChild(bar);

    var body = el('div', 'gr-over-body');
    box.appendChild(body);
    over.appendChild(box);
    over.className = 'gr-overlay is-open';
    document.body.style.overflow = 'hidden';

    /* Rendered into the overlay's own body, so `host` points here and the
       language switch repaints in place rather than into the page behind. */
    if (topic) openTopic(body, topic, closeOverlay);
    else open(body, closeOverlay);

    try { ret.focus(); } catch (e){}
  }

  /* Escape closes the rule and nothing else. Capture and
     stopImmediatePropagation for the same reason lightbox.js needs them:
     nav.js also listens for Escape on `document`, and without this the
     overlay would close AND the screen behind it would leave. */
  document.addEventListener('keydown', function(e){
    if (e.altKey || e.ctrlKey || e.metaKey || e.shiftKey) return;
    if (e.key !== 'Escape' && e.key !== 'Esc') return;
    if (!overlayOpen()) return;
    e.preventDefault();
    e.stopImmediatePropagation();
    closeOverlay();
  }, true);

  return { open:open, openTopic:openTopic,
           overlay:overlay, closeOverlay:closeOverlay, isOverlayOpen:overlayOpen };
})();
