/* Mehrzahl — the plural.

   German plurals look arbitrary and mostly are not. Five endings cover
   nearly everything, and which one a noun takes follows fairly reliably
   from its gender and its ending: feminine nouns in -e take -n without
   exception, -ung and -heit take -en, masculine nouns in -er and -el
   usually take nothing at all. Learning five patterns beats learning a
   hundred and sixty words.

   So the levels teach the pattern before the form. Sorting a word into its
   family is a smaller question than producing the plural, and once the
   family is known the form follows. Asking for the form first is asking
   her to memorise.

   The wrong answers are generated by applying a different pattern to the
   same stem — die Tischer, die Tischen — so every distractor is a plural
   she might plausibly have formed, not a random string.

   Two things the game says out loud because nobody ever tells learners:
   in the plural every noun is die, gender simply stops mattering; and some
   nouns have no plural at all, which is worth knowing before she tries to
   build one. */

window.GH = window.GH || {};

GH.mehrzahl = (function(){

  /* the pattern families, in the order they are worth learning */
  var FAMILIES = [
    { id:'n',     key:'mzFamN'    },   /* -n and -en, the biggest group */
    { id:'e',     key:'mzFamE'    },   /* -e, with or without an umlaut */
    { id:'same',  key:'mzFamSame' },   /* no change, umlaut or not */
    { id:'er',    key:'mzFamEr'   },   /* -er, usually with an umlaut */
    { id:'s',     key:'mzFamS'    }    /* -s, mostly loanwords */
  ];

  /* the raw pattern codes collapse into those five */
  function family(p){
    if (p === 'n' || p === 'en') return 'n';
    if (p === 'e' || p === 'ue') return 'e';
    if (p === 'same' || p === 'usame') return 'same';
    if (p === 'er' || p === 'uer') return 'er';
    if (p === 's') return 's';
    return null;                        /* odd and none sit outside */
  }

  var LEVELS = [
    { id:'form',   key:'mzForm',   hearts:4, rounds:12 },
    { id:'sort',   key:'mzSort',   hearts:4, rounds:12 },
    { id:'umlaut', key:'mzUmlaut', hearts:3, rounds:10 },
    { id:'none',   key:'mzNone',   hearts:4, rounds:10 },
    { id:'mixed',  key:'mzMixed',  hearts:3, rounds:14 }
  ];

  var host = null, state = null;

  function t(k, v){ return GH.i18n.t(k, v); }

  function el(tag, cls, text){
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text !== undefined && text !== null) n.textContent = text;
    return n;
  }

  function bare(s){ return s.split(' ').slice(1).join(' '); }

  /* Which vowel changed, if any: ['o','ö'] for Kopf -> Köpfe, null for
     Fisch -> Fische. Naming the actual letters is worth more than saying
     'the vowel changes', because she can see it in the word. */
  function vowelShift(sg, pl){
    var a = bare(sg), b = bare(pl);
    /* Capitals count. Apfel becomes Äpfel and the shift is on the first
       letter, so a lowercase-only check reported 'the vowel stays' for a
       word whose whole plural is the vowel changing. */
    var PAIRS = [['au','äu'], ['Au','Äu'],
                 ['a','ä'], ['A','Ä'],
                 ['o','ö'], ['O','Ö'],
                 ['u','ü'], ['U','Ü']];
    for (var i = 0; i < PAIRS.length; i++){
      var from = PAIRS[i][0], to = PAIRS[i][1];
      /* real only if folding it back makes the two words agree */
      if (b.indexOf(to) >= 0 && a.indexOf(from) >= 0){
        if (b.split(to).join(from).indexOf(a) === 0){
          return [from.toLowerCase(), to.toLowerCase()];
        }
      }
    }
    return null;
  }

  function umlaut(sg, pl){
    if (!pl) return false;
    var fold = function(x){
      return x.replace(/ä/g,'a').replace(/ö/g,'o').replace(/ü/g,'u')
              .replace(/Ä/g,'A').replace(/Ö/g,'O').replace(/Ü/g,'U');
    };
    var a = bare(sg), b = bare(pl);
    return fold(b).indexOf(fold(a)) === 0 && b.slice(0, a.length) !== a;
  }

  /* ---------- plausible wrong forms ---------- */

  /* Every distractor is the same word run through a different pattern, so
     each one is a plural she could reasonably have built. A random string
     would be rejected on sight and teach nothing. */
  /* German umlauts the stem vowel, and au moves as a unit: Maus becomes
     Mäuse, never Maüse. Taking simply the last vowel produced forms no
     German speaker would write, which made the distractor obviously wrong
     for the wrong reason. */
  function addUmlaut(w){
    if (/au/.test(w)) return w.replace(/au(?!.*au)/, 'äu');
    if (/Au/.test(w)) return w.replace(/Au(?!.*Au)/, 'Äu');
    return w.replace(/([aouAOU])(?!.*[aouAOU])/, function(m){
      return { a:'ä', o:'ö', u:'ü', A:'Ä', O:'Ö', U:'Ü' }[m];
    });
  }

  function forms(sg){
    var w = bare(sg);
    var out = {};
    out.e     = w + 'e';
    out.ue    = addUmlaut(w) + 'e';
    out.er    = w + 'er';
    out.uer   = addUmlaut(w) + 'er';
    /* -e, -el and -er take a bare -n; everything else takes -en */
    out.n     = /(e|el|er)$/.test(w) ? w + 'n' : w + 'en';
    out.en    = out.n;
    out.s     = w + 's';
    out.same  = w;
    out.usame = addUmlaut(w);
    return out;
  }

  function choicesFor(item){
    var want = bare(item.pl);
    var made = forms(item.sg);
    var seen = {}, out = [want];
    seen[want] = 1;
    ['n','e','ue','er','same','s','usame','uer'].forEach(function(k){
      var f = made[k];
      if (!f || seen[f] || out.length >= 4) return;
      seen[f] = 1;
      out.push(f);
    });
    return GH.text.shuffle(out).map(function(x){ return 'die ' + x; });
  }

  /* ---------- rounds ---------- */

  function poolFor(level){
    var all = (window.GH_PLURALS || []);
    if (level.id === 'none'){
      /* half with no plural, half with one, so 'no plural' is a judgement
         rather than the only button she ever presses */
      var no = all.filter(function(x){ return x.p === 'none'; });
      var yes = GH.text.shuffle(all.filter(function(x){ return x.pl; }).slice()).slice(0, no.length);
      return GH.text.shuffle(no.concat(yes));
    }
    if (level.id === 'umlaut'){
      return all.filter(function(x){ return x.pl && ['ue','uer','usame','e','er','same'].indexOf(x.p) >= 0; });
    }
    if (level.id === 'sort'){
      return all.filter(function(x){ return x.pl && family(x.p); });
    }
    return all.filter(function(x){ return x.pl; });
  }

  function build(level){
    var pool = GH.tutor.pick(poolFor(level), level.rounds * 3, function(x){
      /* the word and the family it belongs to — she can know one noun and
         still be lost on the pattern behind it */
      var keys = [];
      if (x.n) keys.push('word:' + x.n);
      var fam = family(x.p);
      if (fam) keys.push('plural:' + fam);
      return keys.length ? keys : null;
    });
    var out = [];
    pool.forEach(function(x){
      if (out.length >= level.rounds) return;
      var kind = level.id;
      if (kind === 'mixed') kind = Math.random() < 0.5 ? 'form' : 'sort';
      if (kind === 'sort' && !family(x.p)) return;
      out.push({ item:x, kind:kind, answered:false, correct:false });
    });
    return out;
  }

  function current(){ return state.items[state.i] || null; }

  function choose(pick){
    var it = current();
    if (!it || it.answered) return;
    it.answered = true;
    it.picked = pick;

    var x = it.item;
    if (it.kind === 'sort')        it.correct = pick === family(x.p);
    else if (it.kind === 'umlaut') it.correct = pick === (umlaut(x.sg, x.pl) ? 'yes' : 'no');
    else if (it.kind === 'none')   it.correct = pick === (x.pl ? 'yes' : 'no');
    else                           it.correct = pick === x.pl;

    if (it.correct) state.score++;
    else { state.hearts--; state.missed.push(it); }
    /* the shared run: streak, percentage, and what to say about it */
    state.run.saw('mz:' + state.i, it.correct);

    if (GH.tutor){
      GH.tutor.grade('skill:plural', it.correct);
      if (x.n) GH.tutor.grade('word:' + x.n, it.correct);
      /* the family, not only the word. Knowing she is weak on plurals is
         not actionable; knowing she is weak on -er plurals is. */
      var fam = family(x.p);
      if (fam) GH.tutor.grade('plural:' + fam, it.correct);
      if (x.p === 'none') GH.tutor.grade('plural:none', it.correct);
      if (umlaut(x.sg, x.pl)) GH.tutor.grade('plural:umlaut', it.correct);
    }
    if (x.pl) GH.speech.say(x.sg + ' … ' + x.pl);
    else GH.speech.say(x.sg);
    paint();
    if (state.hearts <= 0) setTimeout(finish, 900);
  }

  function next(){
    state.i++;
    if (!current()){ finish(); return; }
    paint();
  }

  function finish(){ state.phase = 'done'; paint(); }

  /* ---------- painting ---------- */

  function hearts(){
    var wrap = el('span', 'cw-hearts');
    for (var i = 0; i < state.level.hearts; i++){
      var svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
      svg.setAttribute('viewBox', '0 0 20 20');
      svg.setAttribute('class', 'cw-heart' + (i < state.hearts ? '' : ' spent'));
      var path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
      path.setAttribute('d', 'M10 17.5s-6.5-4.03-8.5-7.86C.36 7.4 1.2 4.4 4 3.4c1.9-.68 3.9.1 5 1.7 1.1-1.6 3.1-2.38 5-1.7 2.8 1 3.64 4 2.5 6.24C16.5 13.47 10 17.5 10 17.5z');
      svg.appendChild(path);
      wrap.appendChild(svg);
    }
    return wrap;
  }

  function question(it){
    var x = it.item;
    var wrap = el('div', 'mz-q');
    if (x.n && GH.sprite){
      var fig = el('div', 'mz-figure');
      fig.appendChild(GH.sprite.tile(x.n));
      wrap.appendChild(fig);
    }
    wrap.appendChild(el('p', 'mz-sg', x.sg));
    var lang = GH.i18n.lang();
    var gloss = lang === 'ru' ? x.ru : x.en;
    if (lang !== 'de' && gloss) wrap.appendChild(el('p', 'mz-gloss', gloss));
    wrap.appendChild(el('p', 'mz-ask', t('mzAsk_' + it.kind)));
    return wrap;
  }

  function options(it){
    var x = it.item;
    var row, opts;

    if (it.kind === 'sort'){
      row = el('div', 'mz-fams');
      opts = FAMILIES.map(function(f){ return [f.id, t(f.key)]; });
    } else if (it.kind === 'umlaut' || it.kind === 'none'){
      row = el('div', 'ww-row');
      opts = it.kind === 'umlaut'
        ? [['yes', t('mzUmlautYes')], ['no', t('mzUmlautNo')]]
        : [['yes', t('mzHasPlural')], ['no', t('mzNoPlural')]];
    } else {
      row = el('div', 'options');
      opts = choicesFor(x).map(function(c){ return [c, c]; });
    }

    opts.forEach(function(o){
      var cls = it.kind === 'sort' ? 'mz-fam'
              : (it.kind === 'umlaut' || it.kind === 'none') ? 'ww-btn' : 'option';
      var b = el('button', cls, o[1]);
      b.type = 'button';
      b.addEventListener('click', function(){ choose(o[0]); });
      row.appendChild(b);
    });
    return row;
  }

  /* what the answer actually was, and why */
  function verdict(it){
    var x = it.item;
    var box = el('div', 'mz-verdict' + (it.correct ? ' is-right' : ''));

    if (x.pl){
      var pair = el('div', 'mz-pair');
      pair.appendChild(el('span', 'mz-pair-sg', x.sg));
      pair.appendChild(el('span', 'mz-pair-arrow', '→'));
      pair.appendChild(el('span', 'mz-pair-pl', x.pl));
      box.appendChild(pair);
      /* Say what happened to this word before describing its family.

         The family note reads 'takes -e, sometimes with an umlaut', which
         is true of the group and useless in front of der Fisch — she is
         left wondering whether this one has an umlaut or not. So the first
         line is about the word she just answered, naming the vowel change
         where there is one and saying plainly when there is not. */
      var f = family(x.p);
      var shift = vowelShift(x.sg, x.pl);
      if (f){
        box.appendChild(el('p', 'mz-why is-this',
          shift ? t('mzThisShift', { end:t('mzEnd_' + f), from:shift[0], to:shift[1] })
                : t('mzThisPlain', { end:t('mzEnd_' + f) })));
        box.appendChild(el('p', 'mz-why', t('mzWhy_' + f)));
      }
      if (x.p === 'odd') box.appendChild(el('p', 'mz-why', t('mzWhyOdd')));
      box.appendChild(el('p', 'mz-die', t('mzAlwaysDie')));
    } else {
      box.appendChild(el('p', 'mz-why', t('mzWhyNone', { w:x.sg })));
    }
    return box;
  }

  function paint(){
    host.textContent = '';

    var head = el('div', 'practice-head');
    var back = el('button', 'backlink', '\u2039 ' + t('back'));
    back.type = 'button';
    back.addEventListener('click', function(){ GH.speech.stop(); state.onExit(); });
    head.appendChild(back);
    var titles = el('div', 'practice-title');
    titles.appendChild(el('h1', null, t('mzTitle')));
    titles.appendChild(el('p', null,
      state.phase === 'pick' ? t('cgPickLevel') : t(state.level.key)));
    head.appendChild(titles);
    if (state.run) head.appendChild(GH.run.header(state.run));
    host.appendChild(head);

    if (state.phase === 'pick'){ paintLevels(); return; }
    if (state.phase === 'done'){ paintDone(); return; }

    var it = current();
    if (!it){ finish(); return; }

    var card = el('div', 'card');
    var status = el('div', 'cw-status');
    status.appendChild(hearts());
    status.appendChild(el('span', 'cw-score',
      t('roundOf', { i:state.i + 1, n:state.items.length })));
    card.appendChild(status);

    card.appendChild(question(it));

    if (!it.answered){
      card.appendChild(options(it));
    } else {
      /* the shared acknowledgement — says more when the streak is
         worth mentioning, and nothing extra when it is not */
      var ack = GH.run.note(state.run);
      if (ack) card.appendChild(ack);
      card.appendChild(verdict(it));
      var go = el('button', 'btn btn-primary js-advance', t('next'));
      go.type = 'button';
      go.addEventListener('click', next);
      var acts = el('div', 'done-actions');
      acts.appendChild(go);
      card.appendChild(acts);
    }

    host.appendChild(card);
    if (it.answered) GH.nav.ready();
  }

  function paintLevels(){
    var tools = el('div', 'card-tools');
    tools.appendChild(GH.howto.button('mzTitle', 'mzRule'));
    host.appendChild(tools);

    var grid = el('div', 'tiles');
    LEVELS.forEach(function(lv){
      var n = poolFor(lv).length;
      var b = el('button', 'tile');
      b.type = 'button';
      b.disabled = n < 4;
      b.appendChild(el('span', 'tile-glyph', '\ud83d\udc65'));
      b.appendChild(el('span', 'tile-name', t(lv.key)));
      b.appendChild(el('span', 'tile-sub', t(lv.key + 'Sub')));
      b.appendChild(el('span', 'tile-foot',
        t('mzWordsN', { n:n }) + ' \u00b7 ' + t('cwHeartsN', { n:lv.hearts })));
      b.addEventListener('click', function(){ begin(lv); });
      grid.appendChild(b);
    });
    host.appendChild(grid);
  }

  function begin(level){
    state.level = level;
    /* Which level this round is, so accuracy can be read per level.
       Without it the tutor cannot choose a difficulty from evidence. */
    if (GH.events && GH.events.setLevel) GH.events.setLevel(level && level.id);
    state.items = build(level);
    state.i = 0;
    state.score = 0;
    state.run = GH.run.create();
    state.hearts = level.hearts;
    state.missed = [];
    state.phase = 'play';
    paint();
  }

  function paintDone(){
    var lost = state.hearts <= 0;
    var clean = !lost && !state.missed.length;
    var lang = GH.i18n.lang();

    /* pay for the round before drawing the screen that reports it */

    var paid = GH.coins ? GH.coins.award('plural', state.run,

      { record: !!state.newBest }) : null;
      /* and anything newly true — checked after the round is counted */
      var won = GH.awards ? GH.awards.afterRound('plural', state.run) : [];

    GH.endScreen.render(host, {
      coins: paid,
      awards: won,
      tone: clean ? 'perfect' : (lost ? 'lost' : 'done'),
      glyph: clean ? '\ud83c\udfc6' : (lost ? '\ud83d\udc94' : '\ud83d\udc65'),
      title: clean ? t('cwPerfect') : (lost ? t('cwOut') : t('doneTitle')),
      stats: [
        { n:state.score, label:t('fbRight'), kind:'good' },
        { n:state.items.length - state.score, label:t('fbWrong'), kind:'bad' }
      ],
      reviews: [{
        head: t('mzMissedHead'),
        tone: 'missed',
        items: state.missed.map(function(it){
          var x = it.item;
          return {
            n: x.n,
            de: x.pl || x.sg,
            gloss: x.pl ? x.sg : t('mzNoPlural'),
            speak: x.pl ? (x.sg + ' … ' + x.pl) : x.sg
          };
        }),
        onTap: function(x){ GH.speech.say(x.speak); }
      }],
      actions: [
        { label:t('again'), kind:'primary', onClick:function(){ begin(state.level); } },
        { label:t('cwChangeLevel'), onClick:function(){ state.phase = 'pick'; paint(); } },
        { label:t('toHub'), onClick:function(){ GH.speech.stop(); state.onExit(); } }
      ]
    });
  }

  function open(container, onExit){
    host = container;
    state = { onExit:onExit, phase:'pick', level:LEVELS[0],
              items:[], i:0, score:0, hearts:0, missed:[] };
    paint();
  }

  /* Its own level ids, read off its own LEVELS array. Declared here rather
     than typed into the entry below, so the two cannot drift apart — the
     tutor picks a level by id, and a stale list means it picks one that
     does not exist. */
  return { open:open, families:FAMILIES, family:family,
           levels:LEVELS.map(function(l){ return l.id; }) };
})();

(function(){
  var entry = {
    id:'mehrzahl',
    glyph:'\ud83d\udc65',
    name:{ ru:'Множественное число', de:'Mehrzahl', en:'Plurals' },
    sub:{ ru:'Пять образцов вместо ста слов',
          de:'Fünf Muster statt hundert Wörter',
          en:'Five patterns instead of a hundred words' },
    /* The rule text this game already ships, so the guide can list
          it without keeping a map that drifts out of date. */
    rules:'mzRule', rulesTitle:'mzTitle',
    /* What the tutor needs to choose FOR her: the ladder, and which areas
       a round here actually grades. `skill:` is omitted — every game
       writes one, so it separates nothing. */
    levels:GH.mehrzahl.levels,
    teaches:['plural', 'word'],
    open:GH.mehrzahl.open
  };
  function register(){ if (window.GH && GH.app && GH.app.register) GH.app.register(entry); }
  if (window.GH && GH.app && GH.app.register) register();
  else if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', register);
  else register();
})();
